// Generated by CoffeeScript 1.12.7
(function() {
  var BrowserDetection, Locale, LocaleModel, QueryString,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  QueryString = (function() {
    function QueryString() {}

    QueryString.get = function(name) {
      var regex, regexS, results;
      if (name) {
        name = name.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
        regexS = "[\\?&]" + name + "=([^&#]*)";
        regex = new RegExp(regexS);
        results = regex.exec(window.location.search);
        if (results === null) {
          return "";
        } else {
          return decodeURIComponent(results[1].replace(/\+/g, " "));
        }
      } else {
        return "";
      }
    };

    return QueryString;

  })();

  LocaleModel = (function(superClass) {
    extend(LocaleModel, superClass);

    function LocaleModel() {
      return LocaleModel.__super__.constructor.apply(this, arguments);
    }

    LocaleModel.prototype.defaults = {
      lang: null,
      strings: null
    };

    return LocaleModel;

  })(Backbone.Model);

  Locale = (function() {
    Locale.prototype.lang = null;

    Locale.prototype.data = null;

    function Locale() {
      this.get = bind(this.get, this);
      this.loadBackup = bind(this.loadBackup, this);
      this.onSuccess = bind(this.onSuccess, this);
      _.extend(this, Backbone.Events);
      this.loadBackup();
      null;
    }

    Locale.prototype.onSuccess = function(event) {
      var d;
      d = null;
      if (event.responseText) {
        d = JSON.parse(event.responseText);
      } else {
        d = event;
      }
      this.data = new LocaleModel(d);
      this.trigger('complete');
      return null;
    };

    Locale.prototype.loadBackup = function() {
      $.ajax({
        url: '/locale/en/strings.txt',
        dataType: 'text',
        complete: this.onSuccess,
        error: (function(_this) {
          return function() {
            return console.log('error on loading backup');
          };
        })(this)
      });
      return null;
    };

    Locale.prototype.get = function(id) {
      return this.data.get('strings')[id] || "";
    };

    return Locale;

  })();

  BrowserDetection = (function() {
    BrowserDetection.prototype.browser = null;

    BrowserDetection.prototype.browserVersion = null;

    BrowserDetection.prototype.gl = null;

    BrowserDetection.prototype.webGL = false;

    BrowserDetection.prototype.webGLContext = false;

    BrowserDetection.prototype.webGLAdvanced = false;

    BrowserDetection.prototype.forcePass = false;

    function BrowserDetection() {
      this.testWebGLContext = bind(this.testWebGLContext, this);
      this.onError = bind(this.onError, this);
      this.onSuccess = bind(this.onSuccess, this);
      this.compare = bind(this.compare, this);
      var error;
      this.browser = BrowserDetect.browser;
      this.browserVersion = BrowserDetect.version;
      try {
        this.webGLContext = this.testWebGLContext();
        this.webGLAdvanced = this.testWebGLAdvancedFeats();
      } catch (error1) {
        error = error1;
      }
      this.webGL = Modernizr.webgl && this.webGLContext;
    }

    BrowserDetection.prototype.init = function() {
      return this.compare();
    };

    BrowserDetection.prototype.compare = function() {
      if (this.forcePass || (this.webGL && this.webGLAdvanced)) {
        return this.onSuccess();
      } else if (!window.WebGLRenderingContext) {
        return this.onError({
          message: 'NoWebGLRenderingContext_message',
          buttons: ['NoWebGLRenderingContext_button1', 'NoWebGLRenderingContext_button2']
        });
      } else if (!this.webGLContext) {
        return this.onError({
          message: 'NoWebGL_message',
          buttons: ['NoWebGL_button1', 'NoWebGL_button2']
        });
      } else {
        return this.onSuccess();
      }
    };

    BrowserDetection.prototype.onSuccess = function() {
      return this.onError({
        message: 'Chrome_NoWebGL_message',
        buttons: ['Chrome_NoWebGL_button1', 'Chrome_NoWebGL_button2']
      });
    };

    BrowserDetection.prototype.onError = function(error) {};

    BrowserDetection.prototype.testWebGLContext = function() {
      var _canvas, error, result;
      result = false;
      try {
        _canvas = document.createElement('canvas');
        if (!(this.gl = _canvas.getContext('experimental-webgl', {
          alpha: 1,
          premultipliedAlpha: true,
          antialias: false,
          stencil: true,
          preserveDrawingBuffer: false
        }))) {
          result = false;
        } else {
          result = true;
        }
      } catch (error1) {
        error = error1;
        result = false;
      }
      return result;
    };

    BrowserDetection.prototype.testWebGLAdvancedFeats = function() {
      var _glExtensionCompressedTextureS3TC, _glExtensionTextureFilterAnisotropic, dxt1Supported, dxt1rgbaSupported, dxt3Supported, dxt5Supported, format, formats, i, len;
      if (this.gl == null) {
        return false;
      }
      _glExtensionCompressedTextureS3TC = this.gl.getExtension('WEBGL_compressed_texture_s3tc') || this.gl.getExtension('MOZ_WEBGL_compressed_texture_s3tc') || this.gl.getExtension('WEBKIT_WEBGL_compressed_texture_s3tc');
      formats = this.gl.getParameter(this.gl.COMPRESSED_TEXTURE_FORMATS);
      dxt5Supported = false;
      dxt3Supported = false;
      dxt1Supported = false;
      dxt1rgbaSupported = false;
      if (formats != null) {
        for (i = 0, len = formats.length; i < len; i++) {
          format = formats[i];
          switch (format) {
            case _glExtensionCompressedTextureS3TC.COMPRESSED_RGBA_S3TC_DXT5_EXT:
              dxt5Supported = true;
              break;
            case _glExtensionCompressedTextureS3TC.COMPRESSED_RGB_S3TC_DXT1_EXT:
              dxt1Supported = true;
              break;
            case _glExtensionCompressedTextureS3TC.COMPRESSED_RGBA_S3TC_DXT1_EXT:
              dxt1rgbaSupported = true;
              break;
            case _glExtensionCompressedTextureS3TC.COMPRESSED_RGBA_S3TC_DXT3_EXT:
              dxt3Supported = true;
          }
        }
      }
      _glExtensionTextureFilterAnisotropic = this.gl.getExtension('EXT_texture_filter_anisotropic') || this.gl.getExtension('MOZ_EXT_texture_filter_anisotropic') || this.gl.getExtension('WEBKIT_EXT_texture_filter_anisotropic');
      return _glExtensionCompressedTextureS3TC && _glExtensionTextureFilterAnisotropic && dxt5Supported && dxt3Supported && dxt1Supported && dxt1rgbaSupported;
    };

    return BrowserDetection;

  })();

  $(function() {
    var img, img2;
    window.error = {};
    window.detection = new BrowserDetection;
    window.detection.forcePass = QueryString.get("forcepass") === "on" ? true : false;
    window.errorMessage = {};
    window.detection.onSuccess = (function(_this) {
      return function() {
        $('#detect').remove();
        (window || document).textureQuality = "med";
        (window || document).displayQuality = "hi";
        (window || document).dof = true;
        return window.onCompleteAnim();
      };
    })(this);
    window.onQuality = (function(_this) {
      return function() {
        var script;
        script = document.createElement('script');
        script.type = 'text/javascript';
        script.src = '/js/r.js';
        return $("head").append(script);
      };
    })(this);
    window.onLowClick = (function(_this) {
      return function() {
        $('.qualityCheck').find('.settings_button').each(function(index, item) {
          $(item).css({
            'cursor': 'default'
          });
          return $(item).click(null);
        });
        (window || document).textureQuality = "low";
        (window || document).displayQuality = "med";
        (window || document).dof = false;
        return $('.qualityCheck').animate({
          opacity: 0
        }, 1000, window.onCompleteAnim);
      };
    })(this);
    window.onHighClick = (function(_this) {
      return function() {
        $('.qualityCheck').find('.settings_button').each(function(index, item) {
          $(item).css({
            'cursor': 'default'
          });
          return $(item).click(null);
        });
        (window || document).textureQuality = "med";
        (window || document).displayQuality = "hi";
        (window || document).dof = true;
        return $('.qualityCheck').animate({
          opacity: 0
        }, 1000, window.onCompleteAnim);
      };
    })(this);
    window.onCompleteAnim = (function(_this) {
      return function() {
        $('.qualityCheck').remove();
        $('#polite').css({
          'display': 'table'
        });
        return onQuality();
      };
    })(this);
    window.detection.onError = (function(_this) {
      return function(error) {
        window.errorMessage = error;
        window.error.locale = new Locale;
        return window.error.locale.on('complete', window.fallbackTemplate);
      };
    })(this);
    window.fallbackTemplate = (function(_this) {
      return function(error) {
        var b, button, c, i, len, ref, results1;
        $('#detect').css({
          display: 'table'
        });
        $('#detect .title').html(window.error.locale.get('homeTitle'));
        $('#detect .errorMessage span').html(window.error.locale.get(window.errorMessage.message));
        window.addGAError();
        ref = window.errorMessage.buttons;
        results1 = [];
        for (i = 0, len = ref.length; i < len; i++) {
          button = ref[i];
          if (window.showTechOrTrailer(button)) {
            c = window.error.locale.get(button + '_url');
            b = $('<a/>');
            b.css({
              'text-decoration': 'none'
            });
            if (button === "FF4_Safari_WebGL_button2") {
              b.click(window.tryAnyway);
            } else {
              b.attr({
                href: window.getHTML5RocksUrl(button, c),
                target: '_blank'
              });
            }
            b.html("<button class='abstractbutton'>" + (window.error.locale.get(button)) + "</button>");
            $('#detect .btnContainer').append(b);
            $('#detect .btnContainer').append("<br>");
            if (navigator.appVersion.indexOf("Win") !== -1) {
              results1.push($(b).css({
                "padding": "7px 20px 8px 20px"
              }));
            } else {
              results1.push(void 0);
            }
          } else {
            results1.push(void 0);
          }
        }
        return results1;
      };
    })(this);
    window.addGAError = (function(_this) {
      return function() {
        return require(["http://google-analytics.com/ga.js"], function() {
          var pageTracker;
          pageTracker = _gat._getTracker("UA-37524215-3");
          return pageTracker._trackPageview('browser_error_page');
        });
      };
    })(this);
    window.getHTML5RocksUrl = (function(_this) {
      return function(label, url) {
        switch (label) {
          case "Chrome_NoWebGL_button2":
          case "FF4_noWebGL_button2":
          case "NoWebGLRenderingContext_button2":
          case "NoWebGL_button2":
            return 'http://www.html5rocks.com/tutorials/casestudies/oz/';
          case 'Chrome_NoWebGL_button1':
          case 'FF4_noWebGL_button1':
          case 'NoWebGLRenderingContext_button1':
          case 'NoWebGL_button1':
            return 'http://www.youtube.com/watch?v=VSyai9suXWc&feature=youtu.be';
          default:
            return url;
        }
      };
    })(this);
    window.showTechOrTrailer = (function(_this) {
      return function(label) {
        return true;
      };
    })(this);
    window.tryAnyway = (function(_this) {
      return function(event) {
        $('head').children().each(function(index, dom) {
          if (dom.src === "http://google-analytics.com/ga.js") {
            return $(dom).remove();
          }
        });
        event.preventDefault();
        return window.detection.onSuccess();
      };
    })(this);
    img = new Image();
    img.src = '/img/home/interface_1x.png';
    if (window.devicePixelRatio === 2) {
      img2 = new Image();
      img2.src = '/img/home/interface_2x.png';
    }
    return window.detection.init();
  });

}).call(this);
